name: Daily News Update

on:
    schedule:
        - cron: "0 10 * * 1"
    workflow_dispatch:

jobs:
    update-news:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install pipenv --user
                  pipenv install

            - name: Set up project directory
              run: |
                  mkdir -p headlines

            - name: Run news script
              env:
                  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
              run: pipenv run python src/news.py

            - name: Commit and push changes
              env:
                  GIT_COMMITTER_NAME: ${{ secrets.NAME }}
                  GIT_COMMITTER_EMAIL: ${{ secrets.EMAIL }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name $GIT_COMMITTER_NAME
                  git config --global user.email $GIT_COMMITTER_EMAIL
                  FILE=$(ls -t headlines/*.csv | head -n 1)
                  FILE_SHA=$(sha1sum $FILE | cut -d ' ' -f 1)
                  git add $FILE
                  git commit -m "$FILE_SHA"
                  git push
